AllCops:
  Exclude:
    - Guardfile
    - vendor/**/*

LineLength:
  Max: 110

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Prevent rubocop from wanting "a" and "e" as block variables
# for reduce and inject... that's retarded in my opinion
Style/SingleLineBlockParams:
  Methods: []
